yarnPath: .yarn/releases/yarn-berry.cjs
enableTelemetry: 0

packageExtensions:
  "@apollo/client@^3.1.5":
    dependencies:
      subscriptions-transport-ws: "*"
    peerDependencies:
      subscriptions-transport-ws: "*"
  graphql-codegen-apollo-next-ssr@*:
    dependencies:
      "graphql": "*"
      "@graphql-codegen/plugin-helpers": "*"
      "@graphql-codegen/visitor-plugin-common": "*"
  babel-plugin-graphql-tag@^3.0.0:
    dependencies:
      "@babel/core": "*"
    peerDependencies:
      "@babel/core": "*"
      graphql-tag: "*"
